FROM python

WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь проект (исключая ненужное через .dockerignore)
COPY . .

# Указываем команду по умолчанию (можно переопределить в docker-compose)
CMD ["alembic", "upgrade", "head"]