version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: pg_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: telegram_bot
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./app/images:/app/images
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  alembic:
    build:
      dockerfile: Dockerfile.alembic
      context: .
    container_name: alembic
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  pg_data: